# Generated by Django 5.0.3 on 2024-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('societe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('telFixe', models.CharField(max_length=20)),
                ('telMobile', models.CharField(max_length=20)),
                ('besoin', models.TextField()),
            ],
        ),
    ]
